"""
diff_analysis.py — Pairwise Diff Analysis Pipeline.

Compares adjacent samples in their natural generation order to identify
what changed between versions and how those changes affect performance.

Usage:
    from framework.knowledge.diff_analysis import analyze_diffs_for_run
    diffs = analyze_diffs_for_run(kb_analysis_path, kb, llm_client)
"""

from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass, field, asdict
from typing import Optional


# ---------------------------------------------------------------------------
#  Data classes
# ---------------------------------------------------------------------------

@dataclass
class PatternChange:
    pattern_id: str               # "PAT-014" or "NEW-001"
    pattern_name: str
    change_type: str              # "added" | "removed" | "intensified" | "weakened"
    what_changed: str
    code_a_evidence: str          # Relevant code from version A ("" if newly added)
    code_b_evidence: str          # Relevant code from version B ("" if removed)
    intensity_from: Optional[int] # 0-3 scale, None if newly added
    intensity_to: Optional[int]   # 0-3 scale, None if removed


@dataclass
class NewPatternCandidate:
    raw_description: str
    mechanism_hypothesis: str
    code_snippet: str
    estimated_impact: str         # "high" | "medium" | "low"


@dataclass
class CausalChain:
    name: str
    trigger: str
    steps: list[str]
    pattern_ids: list[str]
    estimated_effect: str
    note: str


@dataclass
class DiffRecord:
    diff_id: str
    task_id: str

    version_a_id: str
    version_a_path: str
    version_a_speedup: float
    version_a_kernel_time_ms: float

    version_b_id: str
    version_b_path: str
    version_b_speedup: float
    version_b_kernel_time_ms: float

    code_a: str                   # Full source code of version A
    code_b: str                   # Full source code of version B

    speedup_ratio: float          # B/A (>1 = B faster)
    kernel_time_ratio: float      # B/A (<1 = B faster)
    direction: str                # "improvement" | "regression" | "neutral"

    pattern_changes: list[PatternChange]
    unchanged_patterns: list[str]
    new_candidates: list[NewPatternCandidate]

    causal_chains: list[CausalChain]
    agent_summary: str

    model_id: str
    run_name: str
    timestamp: str


# ---------------------------------------------------------------------------
#  Agent prompt
# ---------------------------------------------------------------------------

DIFF_AGENT_SYSTEM = """\
You are a CUDA optimization analyst. You will receive two consecutive versions of
CUDA code for the same task, generated by the same LLM. Your job is to:

1. IDENTIFY what changed in the code between version A and version B
2. CLASSIFY each change: does it match a known optimization pattern from the
   knowledge base? If yes, record the pattern ID. If no, describe it as a new candidate.
3. For changes that match known patterns, note whether the pattern was added, removed,
   or changed in intensity (e.g., template params went from 1 to 3)
4. ANALYZE whether multiple changes form a causal chain (removing one would break others)
5. SUMMARIZE: what is the overall optimization strategy difference between A and B?

IMPORTANT:
- Version B may be FASTER or SLOWER than A. A regression is valid data.
- Focus on CODE DIFFERENCES, not on what each version does independently.
- CUDA optimizations are often interdependent. Template specialization enabling
  register promotion enabling loop reordering is ONE causal chain, not three
  independent changes.
- intensity_from and intensity_to are integers 0-3. 0=absent, 1=minimal, 2=moderate, 3=extensive.

Output strict JSON (no markdown fences, no trailing commas).
{{
  "pattern_changes": [
    {{
      "pattern_id": "PAT-XXX or NEW-001",
      "pattern_name": "name",
      "change_type": "added | removed | intensified | weakened",
      "what_changed": "specific description of the code change",
      "code_a_evidence": "relevant lines from A (or empty if added)",
      "code_b_evidence": "relevant lines from B (or empty if removed)",
      "intensity_from": null or 0-3,
      "intensity_to": null or 0-3
    }}
  ],
  "unchanged_patterns": ["PAT-XXX", ...],
  "new_candidates": [
    {{
      "raw_description": "what the new pattern does",
      "mechanism_hypothesis": "why it affects performance",
      "code_snippet": "relevant code",
      "estimated_impact": "high | medium | low"
    }}
  ],
  "causal_chains": [
    {{
      "name": "descriptive name",
      "trigger": "the root change",
      "steps": ["consequence 1", "consequence 2"],
      "pattern_ids": ["PAT-XXX"],
      "estimated_effect": "~Nx or major/minor",
      "note": "why inseparable"
    }}
  ],
  "summary": "1-2 sentences: what is the key difference between A and B and why does it affect performance"
}}
"""

DIFF_AGENT_USER = """\
## Task: {task_id}
## Version A: {version_a_id} (speedup={speedup_a:.1f}x, kernel_time={kt_a:.1f}ms)
## Version B: {version_b_id} (speedup={speedup_b:.1f}x, kernel_time={kt_b:.1f}ms)
## Performance change: {direction} ({ratio:.2f}x)

## Version A code:
```cuda
{code_a}
```

## Version B code:
```cuda
{code_b}
```

## Version A detected patterns: {patterns_a_summary}
## Version B detected patterns: {patterns_b_summary}

## Auto-features diff:
{features_diff}

## Known optimization patterns in knowledge base:
{kb_patterns_summary}
"""


# ---------------------------------------------------------------------------
#  Helpers
# ---------------------------------------------------------------------------

_diff_counter = 0


def _next_diff_id() -> str:
    global _diff_counter
    _diff_counter += 1
    return f"DIFF-{_diff_counter:04d}"


def _now_ts() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def _compute_features_diff(features_a: dict, features_b: dict) -> str:
    all_keys = sorted(set(list(features_a.keys()) + list(features_b.keys())))
    lines = []
    for k in all_keys:
        va = features_a.get(k)
        vb = features_b.get(k)
        if va != vb:
            lines.append(f"  {k}: {va} -> {vb}")
    return "\n".join(lines) if lines else "  (no differences)"


def _format_patterns_summary(matched_patterns: list[dict]) -> str:
    parts = []
    for p in matched_patterns:
        pid = p.get("pattern_id", "?")
        pname = p.get("pattern_name", "")
        parts.append(f"{pid}({pname})")
    return ", ".join(parts) if parts else "(none)"


def _read_source(path: str, max_chars: int = 10000) -> str:
    if not path or not os.path.exists(path):
        return "(source not found)"
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        content = f.read()
    if len(content) > max_chars:
        content = content[:max_chars] + "\n... [TRUNCATED]"
    return content


def _parse_json_response(text: str) -> dict:
    """Parse JSON from LLM response, handling markdown fences and truncation."""
    import re
    if not text:
        return {}
    text = text.strip()
    # Strip markdown fences
    m = re.search(r'```(?:json)?\s*\n?(.*?)```', text, re.DOTALL)
    if m:
        text = m.group(1).strip()
    # Try direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    # Try finding the outermost JSON object
    start = text.find('{')
    if start >= 0:
        depth = 0
        last_close = -1
        for i in range(start, len(text)):
            if text[i] == '{':
                depth += 1
            elif text[i] == '}':
                depth -= 1
                if depth == 0:
                    last_close = i
                    break
        if last_close > start:
            try:
                return json.loads(text[start:last_close+1])
            except json.JSONDecodeError:
                pass
        # JSON may be truncated by max_tokens — try to repair
        # Close all open brackets/braces
        fragment = text[start:]
        # Remove trailing incomplete string/value
        fragment = re.sub(r',\s*"[^"]*$', '', fragment)
        fragment = re.sub(r',\s*$', '', fragment)
        # Count unclosed braces/brackets
        open_braces = fragment.count('{') - fragment.count('}')
        open_brackets = fragment.count('[') - fragment.count(']')
        fragment += ']' * max(open_brackets, 0) + '}' * max(open_braces, 0)
        try:
            return json.loads(fragment)
        except json.JSONDecodeError:
            pass
    return {}


# ---------------------------------------------------------------------------
#  Core: generate one diff
# ---------------------------------------------------------------------------

def generate_diff(
    task_id: str,
    sample_a: dict,
    sample_b: dict,
    kb,
    model_id: str,
    run_name: str,
    llm_client=None,
    agent_model_id: str = "gemini-3.1-pro-preview-openrouter",
) -> DiffRecord:
    """
    Generate a DiffRecord for one adjacent pair. One LLM call.
    """
    speedup_a = sample_a.get("speedup_e2e", 0)
    speedup_b = sample_b.get("speedup_e2e", 0)
    kt_a = sample_a.get("kernel_time_ms", 0) or 0
    kt_b = sample_b.get("kernel_time_ms", 0) or 0

    ratio = speedup_b / max(speedup_a, 0.001)
    kt_ratio = kt_b / max(kt_a, 0.001)

    if ratio > 1.1:
        direction = "improvement"
    elif ratio < 0.9:
        direction = "regression"
    else:
        direction = "neutral"

    # Resolve source paths
    # In kb_analysis.json, tasks store source_path or we infer from run dir
    path_a = sample_a.get("source_path", "")
    path_b = sample_b.get("source_path", "")

    code_a = _read_source(path_a)
    code_b = _read_source(path_b)

    pats_a = _format_patterns_summary(sample_a.get("matched_patterns", []))
    pats_b = _format_patterns_summary(sample_b.get("matched_patterns", []))

    features_diff = _compute_features_diff(
        sample_a.get("auto_features", {}),
        sample_b.get("auto_features", {}),
    )

    # Get LLM client
    if llm_client is None:
        from ..llm.registry import LLMRegistry
        registry = LLMRegistry()
        llm_client = registry.get_client(agent_model_id)

    system = DIFF_AGENT_SYSTEM
    user = DIFF_AGENT_USER.format(
        task_id=task_id,
        version_a_id=f"sample_{sample_a.get('sample_id', '?')}",
        version_b_id=f"sample_{sample_b.get('sample_id', '?')}",
        speedup_a=speedup_a,
        speedup_b=speedup_b,
        kt_a=kt_a,
        kt_b=kt_b,
        direction=direction,
        ratio=ratio,
        code_a=code_a,
        code_b=code_b,
        patterns_a_summary=pats_a,
        patterns_b_summary=pats_b,
        features_diff=features_diff,
        kb_patterns_summary=kb.summary_for_agent(),
    )

    resp = llm_client.generate(
        prompt=f"{system}\n\n{user}",
        max_tokens=16000,
        temperature=0.0,
    )
    raw_content = resp.content or ""
    result = _parse_json_response(raw_content)

    if not result:
        # Log the raw response for debugging
        print(f"  [DIFF] WARNING: Could not parse agent response ({len(raw_content)} chars)")
        print(f"  [DIFF] Response preview: {raw_content[:300]}")
        result = {}

    # Build DiffRecord
    pattern_changes = []
    for c in result.get("pattern_changes", []):
        try:
            pattern_changes.append(PatternChange(
                pattern_id=c.get("pattern_id", "?"),
                pattern_name=c.get("pattern_name", ""),
                change_type=c.get("change_type", "?"),
                what_changed=c.get("what_changed", ""),
                code_a_evidence=c.get("code_a_evidence", ""),
                code_b_evidence=c.get("code_b_evidence", ""),
                intensity_from=c.get("intensity_from"),
                intensity_to=c.get("intensity_to"),
            ))
        except Exception:
            continue

    new_candidates = []
    for nc in result.get("new_candidates", []):
        try:
            new_candidates.append(NewPatternCandidate(
                raw_description=nc.get("raw_description", ""),
                mechanism_hypothesis=nc.get("mechanism_hypothesis", ""),
                code_snippet=nc.get("code_snippet", ""),
                estimated_impact=nc.get("estimated_impact", "low"),
            ))
        except Exception:
            continue

    causal_chains = []
    for cc in result.get("causal_chains", []):
        try:
            causal_chains.append(CausalChain(
                name=cc.get("name", ""),
                trigger=cc.get("trigger", ""),
                steps=cc.get("steps", []),
                pattern_ids=cc.get("pattern_ids", []),
                estimated_effect=cc.get("estimated_effect", ""),
                note=cc.get("note", ""),
            ))
        except Exception:
            continue

    return DiffRecord(
        diff_id=_next_diff_id(),
        task_id=task_id,
        version_a_id=f"sample_{sample_a.get('sample_id', '?')}",
        version_a_path=path_a,
        version_a_speedup=speedup_a,
        version_a_kernel_time_ms=kt_a,
        version_b_id=f"sample_{sample_b.get('sample_id', '?')}",
        version_b_path=path_b,
        version_b_speedup=speedup_b,
        version_b_kernel_time_ms=kt_b,
        code_a=_read_source(path_a, max_chars=50000),
        code_b=_read_source(path_b, max_chars=50000),
        speedup_ratio=ratio,
        kernel_time_ratio=kt_ratio,
        direction=direction,
        pattern_changes=pattern_changes,
        unchanged_patterns=result.get("unchanged_patterns", []),
        new_candidates=new_candidates,
        causal_chains=causal_chains,
        agent_summary=result.get("summary", ""),
        model_id=model_id,
        run_name=run_name,
        timestamp=_now_ts(),
    )


# ---------------------------------------------------------------------------
#  Main entry point
# ---------------------------------------------------------------------------

def analyze_diffs_for_run(
    kb_analysis_path: str,
    knowledge_base,
    enable_agent: bool = True,
    agent_model_id: str = "gemini-3.1-pro-preview-openrouter",
    llm_client=None,
) -> list[DiffRecord]:
    """
    Analyze pairwise diffs for a completed run using its kb_analysis.json.

    Groups samples by task_id, orders by sample_id, compares adjacent
    valid (compiled + correct) pairs.
    """
    with open(kb_analysis_path) as f:
        analysis = json.load(f)

    run_name = analysis.get("run_name", "")
    model_id = analysis.get("model_id", "")
    run_dir = os.path.dirname(kb_analysis_path)

    tasks = analysis.get("tasks", [])

    # Group by task_id
    by_task: dict[str, list[dict]] = {}
    for t in tasks:
        if t.get("status") != "analyzed":
            continue
        tid = t.get("task_id", "")
        by_task.setdefault(tid, []).append(t)

    all_diffs: list[DiffRecord] = []

    for task_id, samples in sorted(by_task.items()):
        # Sort by sample_id
        samples = sorted(samples, key=lambda s: s.get("sample_id", 0))

        if len(samples) < 2:
            continue

        # Infer source paths if not present
        for s in samples:
            if not s.get("source_path"):
                sid = s.get("sample_id", 0)
                # Try agent naming convention: agent_r{rep}_t{turn}.cu
                # sample_id = rep * 1000 + turn
                rep = sid // 1000
                turn = sid % 1000
                candidate = os.path.join(run_dir, task_id, f"agent_r{rep}_t{turn}.cu")
                if os.path.exists(candidate):
                    s["source_path"] = candidate

        # Select adjacent pairs
        pairs = [(samples[i], samples[i+1]) for i in range(len(samples) - 1)]

        print(f"[DIFF] {task_id}: {len(pairs)} pairs to analyze")

        for sample_a, sample_b in pairs:
            sid_a = sample_a.get("sample_id", "?")
            sid_b = sample_b.get("sample_id", "?")
            spd_a = sample_a.get("speedup_e2e", 0)
            spd_b = sample_b.get("speedup_e2e", 0)

            print(f"  [DIFF] {task_id} sample_{sid_a} ({spd_a:.1f}x) -> sample_{sid_b} ({spd_b:.1f}x)...")

            if not enable_agent:
                # Auto-only: just record the delta
                ratio = spd_b / max(spd_a, 0.001)
                direction = "improvement" if ratio > 1.1 else ("regression" if ratio < 0.9 else "neutral")
                diff = DiffRecord(
                    diff_id=_next_diff_id(),
                    task_id=task_id,
                    version_a_id=f"sample_{sid_a}",
                    version_a_path=sample_a.get("source_path", ""),
                    version_a_speedup=spd_a,
                    version_a_kernel_time_ms=sample_a.get("kernel_time_ms", 0) or 0,
                    version_b_id=f"sample_{sid_b}",
                    version_b_path=sample_b.get("source_path", ""),
                    version_b_speedup=spd_b,
                    version_b_kernel_time_ms=sample_b.get("kernel_time_ms", 0) or 0,
                    code_a=_read_source(sample_a.get("source_path", ""), max_chars=50000),
                    code_b=_read_source(sample_b.get("source_path", ""), max_chars=50000),
                    speedup_ratio=ratio,
                    kernel_time_ratio=(sample_b.get("kernel_time_ms", 1) or 1) / max(sample_a.get("kernel_time_ms", 1) or 1, 0.001),
                    direction=direction,
                    pattern_changes=[],
                    unchanged_patterns=[],
                    new_candidates=[],
                    causal_chains=[],
                    agent_summary="(agent disabled)",
                    model_id=model_id,
                    run_name=run_name,
                    timestamp=_now_ts(),
                )
                all_diffs.append(diff)
                continue

            try:
                diff = generate_diff(
                    task_id=task_id,
                    sample_a=sample_a,
                    sample_b=sample_b,
                    kb=knowledge_base,
                    model_id=model_id,
                    run_name=run_name,
                    llm_client=llm_client,
                    agent_model_id=agent_model_id,
                )
                all_diffs.append(diff)
                n_changes = len(diff.pattern_changes)
                n_chains = len(diff.causal_chains)
                print(f"    {diff.direction} ({diff.speedup_ratio:.2f}x): "
                      f"{n_changes} pattern changes, {n_chains} causal chains")

                # Feed new candidates to KB staging
                from .store import StagingCandidate, Evidence
                for cand in diff.new_candidates:
                    sc = StagingCandidate(
                        id=knowledge_base._next_candidate_id(),
                        raw_description=cand.raw_description,
                        mechanism_hypothesis=cand.mechanism_hypothesis,
                        code_snippet=cand.code_snippet,
                        evidence=[Evidence(
                            task_id=task_id,
                            model_id=model_id,
                            run_name=run_name,
                            sample_id=sample_b.get("sample_id", 0),
                            speedup_e2e=spd_b,
                            timestamp=_now_ts(),
                        )],
                        created_at=_now_ts(),
                    )
                    knowledge_base.add_candidate(sc)

            except Exception as e:
                print(f"    FAILED: {e}")

    # Save diffs to run directory
    if all_diffs:
        diffs_path = os.path.join(run_dir, "kb_diffs.json")
        with open(diffs_path, "w") as f:
            json.dump([asdict(d) for d in all_diffs], f, indent=2, ensure_ascii=False)
        print(f"\n[DIFF] Saved {len(all_diffs)} diffs to {diffs_path}")

        # Also append to global diffs JSONL
        global_diffs_dir = os.path.join(
            os.path.dirname(os.path.dirname(run_dir)),
            "Library", "knowledge_data", "diffs"
        )
        os.makedirs(global_diffs_dir, exist_ok=True)
        global_path = os.path.join(global_diffs_dir, f"{run_name}.diffs.jsonl")
        with open(global_path, "w") as f:
            for d in all_diffs:
                f.write(json.dumps(asdict(d), ensure_ascii=False) + "\n")
        print(f"[DIFF] Global diffs saved to {global_path}")

    return all_diffs
